apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  strategy: {}
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - env:
            - name: ZIPKIN_URL
              valueFrom:
                configMapKeyRef:
                  name : services-common-config
                  key :  zipkinUrl
            - name: SPRING_PROFILES_ACTIVE
              value: test
          image: api-gateway:1.1
          name: api-gateway
          ports:
            - containerPort: 8083
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30000
  selector:
    app: api-gateway
