apiVersion: v1
kind: Service
metadata:
    name: mysql
spec:
    ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
    name: mysql
subsets:
    - addresses:
        - ip: 192.168.1.5
      ports:
        - port: 3306          
          