apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-broker:9092
#              valueFrom:
#                configMapKeyRef :
#                  name : kafka-config
#                  key :  kafkaAdvertisedListeners  
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT
#              valueFrom:
#                configMapKeyRef :
#                  name : kafka-config
#                  key :  kafkaListenerSecurityProtocol
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef :
                  name : kafka-config
                  key :  kafkaBrokerId      
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              valueFrom:
                configMapKeyRef :
                  name : kafka-config
                  key :  kafkaTransactionStateLogMinIsr
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef :
                  name : kafka-config
                  key :  kafkaOffsetTopicReplicationFactor      
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef :
                  name : kafka-config
                  key :  kafkaTransactionStateLogReplicationFactor
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef :
                  name : kafka-config
                  key :  kafkaZookeeperConnection
          image: confluentinc/cp-kafka:7.0.1
          imagePullPolicy: IfNotPresent
          name: kafka-broker
          ports:
            - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
#  annotations:
#    kompose.cmd: F:\tools\kompose.exe convert
#    kompose.version: 1.26.1 (a9d05d509)
#  creationTimestamp: null
  labels:
    app: kafka-broker
  name: kafka-broker
spec:  
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092      
  selector:
    app: kafka-broker