apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              valueFrom:
                configMapKeyRef :
                  name : zookeeper-config
                  key :  zookeeperClientPort
            - name: ZOOKEEPER_TICK_TIME
              valueFrom:
                configMapKeyRef :
                  name : zookeeper-config
                  key :  zookeeperTickTime
          image: confluentinc/cp-zookeeper:7.0.1
          imagePullPolicy: IfNotPresent
          name: zookeeper
          ports:
           - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8090